spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-empty-firefly-a4ioiv8w.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_6mMz9QOoZavy}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:kkahir2710@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:viqzhcoecukjyklw}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=${SERVER_PORT:8080}

# CORS Configuration
ems.cors.allowed-origin=${ALLOWED_ORIGIN:https://kaushik2710.github.io}